name: blue_hacks_kuwento
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  chewie: ^0.9.7

flutter:
  uses-material-design: true
  assets:
    - assets/home.png
    - assets/download.png
    - assets/film.png
    - assets/hatdog.jpeg
    - assets/checked.png
    - assets/home2.png
    - assets/splash_screen_title.png
    - assets/alam1_alamat.mp4
  fonts:
  - family: Montserrat-Regular
    fonts:
    - asset: assets/Montserrat-Regular.ttf

